### ISSUE TITLE
Problème avec la page Login

### ISSUE THREAD

**Issue by mhdevfr** [mhdevfr/NuxtProject#1]
Erreur 

J'ai une erreur sur ma page 'Login' et sur tout mon contenu en général de mon projet NuxtJS.
J'utilise comme systeme de back-end  Supabase et je suis en train de créer une fonction permettant d'accéder au contenu de mon App SI et seulement SI l'individu est connecté , pour cela j'ai donc choisis d'utiliser une API OAuth celle de Github incluse directement sur Supabase cependant après avoir fais le lien entre mon compte Supabase et mon App lorsque que j'invoque ma fonction "loginWithGithub" permettant à l'utilisateur de se connecter avec Github, mon URL change pendant 1 fraction de seconde passant de localhost:3000/login à localhost:3000/login? mais rien ne se passe, je n'arrive pas à comprendre correctement ou j'ai effectué mon erreur et j'aimerai un petit peu d'aide.

merci de votre compréhension

**Comment by TonyFresneau** [comment]
@mhdevfr 

Quelles sont les différences entre ces deux lignes ?

```
const client = useSupabaseClient()
const user = useSupabaseClient()
```


Pour le reste suit la doc **(il faut toujours suivre et lire la doc)** : https://supabase.nuxtjs.org/usage/composables/usesupabaseclient

```
<script setup lang="ts">
const supabase = useSupabaseClient()

const signInWithOAuth = async () => {
  const { error } = await supabase.auth.signInWithOAuth({
    provider: 'github',
    options: {
      redirectTo: 'http://localhost:3000/confirm',
    },
  })
  if (error) console.log(error)
}

const signOut = async () => {
  const { error } = await supabase.auth.signOut()
  if (error) console.log(error)
}
</script>
```

Ensuite tu utilise `signInWithOAuth` sur un click sur un bouton.

Attention à ton code, il y a des erreurs de frappes : 

```
<button 
  @click='client.auth.signIn({ provider: "Github "})'
  class="text-center rounded h-8 min-w-48 mb-8 bg-green-400">
  Connexion
  </button>
```

Il y a un espace après "Github" et "Github" doit être écris en minuscule comme dans la doc don "github", essayes d'être toujours très propre dans l'écriture de ton code.

**Comment by mhdevfr** [comment]
@Aurion72 

Pour les 2 lignes c'est une erreur de ma part merci de l'avoir notifier.

`const client = useSupabaseClient()
const user = useSupabaseClient()`

J'ai réglé une partie de soucis, maintenant il ne s'agit plus qu'une question de temps car jai un petit peu abusé des Supabase request donc je dois attendre.. 

Merci de ton aide.
